version: 0.2

env:
  variables:
    TF_VERSION: "1.6.0"
    ENV: "dev"  # overridden by CodePipeline for prod

phases:
  install:
    commands:
      - echo Installing Terraform $TF_VERSION...
      - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - cd envs/$ENV
      - terraform init
      - terraform workspace select $ENV || terraform workspace new $ENV

  build:
    commands:
      - terraform fmt -check
      - terraform validate
      - terraform plan -input=false -out=tfplan

  post_build:
    commands:
      - if [ "$APPLY_CHANGES" = "true" ]; then terraform apply -input=false -auto-approve tfplan; fi
