version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - cd envs/prod
      - terraform init
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - terraform estroy -auto-approve
  pre_build:
    commands:
      - cd envs/dev
      - terraform init
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - terraform estroy -auto-approve
